### ISSUE TITLE
Is there any plan to support PHP^8.0 anytime soon?

### ISSUE THREAD

**Issue by Aerendir** [icecave/parity#16]
As per the object, Is there any plan to support PHP^8.0 anytime soon?

**Comment by jmalloc** [comment]
I will look into this as soon as time permits.  I don't use these PHP libraries in my day job any longer, but I do intend to continue maintaining them. Thanks for the report!

**Comment by jmalloc** [comment]
Blocked by:

- [ ] https://github.com/mlively/Phake/issues/289

**Comment by jmalloc** [comment]
Tag [v3.0.1](https://github.com/icecave/parity/releases/tag/3.0.1) works with PHP v8.

**Comment by Aerendir** [comment]
Thank you!
